### ISSUE TITLE
Is the frobenius norm formula wrong in the paper TATU?

### ISSUE THREAD

**Issue by andaolong** [pipixiaqishi1/TATU#1]
Is the formula for calculating frobenius norm wrong on page 4 of the paper? Each element should be squared, then summed and then squared. What you wrote is to take the absolute value, then summed and then squared.

**Comment by pipixiaqishi1** [comment]
Hi,
Thank you for mentioning that to help us fix this error! If you have any other confusion about our work, feel free to contact us.
